### ISSUE TITLE
Dev server error?

### ISSUE THREAD

**Issue by varenius** [appolloford/salsa-ts#4]
Trying to install on SALSA webserver. With "npm install" and then "npm start" I get
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/var/www/html/dev/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/html/dev/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/html/dev/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/html/dev/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/html/dev/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/html/dev/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/html/dev/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/var/www/html/dev/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/var/www/html/dev/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/var/www/html/dev/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/html/dev/node_modules/webpack/lib/NormalModule.js:417:16)
    at /var/www/html/dev/node_modules/webpack/lib/NormalModule.js:452:10
    at /var/www/html/dev/node_modules/webpack/lib/NormalModule.js:323:13
    at /var/www/html/dev/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /var/www/html/dev/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/var/www/html/dev/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/dev/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
```

Ideas?

**Comment by varenius** [comment]
Google led me to a workaround fix at https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported which was to, before npm start, run `export NODE_OPTIONS=--openssl-legacy-provider`. That solved the error above!

But when the server started, I also got these notes:
```
src/App.tsx
  Line 2:21:   'HTMLSelect' is defined but never used              @typescript-eslint/no-unused-vars
  Line 2:33:   'Slider' is defined but never used                  @typescript-eslint/no-unused-vars
  Line 2:41:   'Switch' is defined but never used                  @typescript-eslint/no-unused-vars
  Line 38:22:  'setXPrecision' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/components/Canvas.tsx
  Line 167:10:  'draggedPoint' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/components/Viewer.tsx
  Line 1:10:  'useRef' is defined but never used               @typescript-eslint/no-unused-vars
  Line 2:10:  'Button' is defined but never used               @typescript-eslint/no-unused-vars
  Line 2:18:  'HTMLTable' is defined but never used            @typescript-eslint/no-unused-vars
  Line 42:9:  'fileName' is assigned a value but never used    @typescript-eslint/no-unused-vars
  Line 46:9:  'xPrecision' is assigned a value but never used  @typescript-eslint/no-unused-vars


```
